name: Notify Slack on Release

on:
  release:
    types:
      - created

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Notify Slack on Release
    steps:
      - name: Notify Slack on Release
        uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url:  ${{secret.SLACK_RELEASE_CHANNEL}}
          slack_channel: test
        if: always()
