name: Notify Slack on Release

on:
  push:
    types:
      - created

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Notify Slack on Release
    steps:
      - name: Notify Slack on Release
        uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url:  https://hooks.slack.com/services/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 
        if: always()
