name: Notify Slack on Release

on:
  release:
    types:
      - created

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Notify Slack on Release
    steps:
      - name: Notify Slack on Release
        uses: instantish/notify-slack-on-release@1.0.0
        with:
          slack_webhook_url:  https://hooks.slack.com/services/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 
          slack channel: test
        if: always()
