on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Slack Notification Demo
        uses: craftech-io/slack-action@v1
        env:
          GITHUB_ACTOR: ${GITHUB_ACTOR}
          GITHUB_ACTION: ${GITHUB_ACTION}
          GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}
          GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
          GITHUB_REF: ${GITHUB_REF}
          GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}
          SLACK_CHANNEL: 'test'
          SLACK_COLOR: '#efefef'
          SLACK_ICON: 'https://github.com/<Github User>.png?size=48'
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_RELEASE_CHANNEL }}
          SLACK_MESSAGE: 'Demo''ing the Slack Notification'
          SLACK_TITLE: 'Slack Notification Demo'
      
